language: php
cache: false

sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

before_script:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly